apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-stage
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/willianBinda/argoCD-SOPS-PGP.git
    targetRevision: stage
    path: enviroments/stage
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true