apiVersion: v1
kind: Service
metadata:
  name: api-rest-java-jib-svc
spec:
  type: NodePort #pode ser modificado para ClusterIP interno
  selector:
    app: api-rest-java-jib-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-java-jib-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rest-java-jib-pod
  template:
    metadata:
      labels:
        app: api-rest-java-jib-pod
    spec:
      containers:
        - name: api-rest-java
          image: sua-imagem-dockerHub # adicione sua imagem no dockerHub
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgres_host
                  name: microsservices-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: postgres_port
                  name: microsservices-config
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: postgres_dbname
                  name: microsservices-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postgres_username
                  name: microsservices-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: microsservices-secrets
