name: (Stage) Update version acesso

on:
  pull_request:
    types:
      - opened
    branches:
      - stage
    paths:
      - "microsservices/apiRestJava/**"
env:
  API_VERSION: ""
  SHOULD_BUILD: "false"

jobs:
  build:
    if: github.base_ref == 'stage' && github.head_ref == 'development'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          curl -sLo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.17.2/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Extract image version
        run: |
          # Extract the image version from the YAML file
          version=$(yq e '.spec.template.spec.containers[] | select(.name == "api-rest-acesso") | .image | split(":") | .[1]' enviroments/stage/3-api-rest-java.yaml)
          echo "API_VERSION=$version" >> $GITHUB_ENV

      - name: Log Old Version Acesso
        run: |
          echo "Old version acesso extracted: ${{ env.API_VERSION }}"

      - name: Set New Image Version
        uses: actions/github-script@v6
        with:
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            let envValue = process.env.API_VERSION;

            let [major, minor, patch] = envValue.split('.').map(Number);

            let shouldIncrementMinor = false;
            let shouldIncrementPatch = false;
            let updated = false;  // Flag to track if version should be updated


            const directoriesOfInterest = [
              'microsservices/acesso/',
            ];

            for (const commit of commits) {
              const { data: commitDetails } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commit.sha,
              });

              const isInDirectoryOfInterest = commitDetails.files.some(file => 
                directoriesOfInterest.some(dir => file.filename.startsWith(dir))
              );

              const message = commit.commit.message;

              const featRegex = /(?:\[.*?\]\s*)?feat:/;
              const fixRegex = /(?:\[.*?\]\s*)?fix:/;
              const perfRegex = /(?:\[.*?\]\s*)?perf:/;

              if ((featRegex.test(message) || perfRegex.test(message)) && isInDirectoryOfInterest) {
                shouldIncrementMinor = true;
                break;
              } else if (fixRegex.test(message) && isInDirectoryOfInterest) {
                shouldIncrementPatch = true;
              }
            }

            if (shouldIncrementMinor) {
              minor += 1;
              patch = 0;
              updated = true;
            } else if (shouldIncrementPatch) {
              patch += 1;
              updated = true;
            }

            if (updated) {
              const newVersion = `${major}.${minor}.${patch}`;
              core.exportVariable('API_VERSION', newVersion);
              core.exportVariable('SHOULD_BUILD', 'true');
            } else {
              core.exportVariable('SHOULD_BUILD', 'false');
            }

      - name: Log Should build and new Version
        run: |
          echo "New version acesso: ${{ env.API_VERSION }}"
          echo "Should build: ${{ env.SHOULD_BUILD }}"

      - name: Setup Java JDK
        if: env.SHOULD_BUILD == 'true'
        uses: actions/setup-java@v4.2.2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      # Build and install dependencies
      # - name: Build and install dependencies
      #   if: env.SHOULD_BUILD == 'true'
      #   run: |
      #     cd microsservices/dto-comum
      #     ./mvnw clean install -DskipTests
      #     cd ../entity-comum
      #     ./mvnw clean install -DskipTests
      #     cd -

      # Build microservice
      - name: Build microservice
        if: env.SHOULD_BUILD == 'true'
        run: |
          cd microsservices/acesso
          ./mvnw clean package -DskipTests
          cd -

      - name: Docker Login
        if: env.SHOULD_BUILD == 'true'
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        if: env.SHOULD_BUILD == 'true'
        uses: docker/build-push-action@v6.7.0
        with:
          context: microsservices/acesso
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/stage-api-rest-java:${{ env.API_VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/stage-api-rest-java:latest
